### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by Chantreck** [Sturm-noob/AndroidCalculator#1]
В первом ревью сосредоточимся на вёрстке и работе с UI-элементами

**XML:**
1. Для чего нужна такая вложенность `ConstraintLayout`? Его главное преимущество как раз в том, что всё можно спокойно разместить в одном лэйауте без лишней вложенности
2. Для кнопок не стоит использовать `ImageView`, лучше использовать обычные кнопки или `ImageButton`
3. У кнопок много повторяющихся атрибутов, которые можно и нужно вынести в стили. Например, `backgroundTint`, `fontFamily`, `inset*`, `textColor`, `textSize`, `cornerRadius`. И зачем используется такая запись
```xml
android:layout_height="0dp"
android:height="100dp"
```
Высоту нужно чем-то одним задавать

**MainActivity**:
1. Не стоит использовать `lateinit`, использование его имеет некоторые неудобства. В случае с `binding` можно записать так:
```kotlin
val binding by lazy { ActivityMainBinding.inflate(layoutInflater) }
```
Благодаря `lazy` `binding` будет проинициализирован при первом обращении к нему, то есть в `onCreate` и поэтому никаких ошибок не возникнет. Классы `Solver` и `SolverContainer` можно сразу проинициализировать или через тот же `lazy`

2. Не очень понял, почему возникла `LiveData` в активити. Результат вычислений должен храниться в классе с вычислениями, поэтому и `LiveData` должна находиться где-то там, если мы не используем `ViewModel`. Но в данном случае она используется только внутри активити, а этого точно не должно быть. `LiveData` используется для передачи данных между классами/слоями, а не внутри одного класса, это оверхед. Для этого достаточно просто завести функцию, которая будет делать нужные действия при изменении данных, и вызывать её вместо изменения данных в `LiveData`

3. К слову её тоже можно и нужно сразу инициализировать, только лучше использовать вот такую запись:
```kotlin
private val _input = MutableLiveData<String>()
val input: LiveData<String> get() = _input
```
Таким образом, внешний подписчик сможет получать данные только на чтение и точно не сможет их изменить

4. Немного необычная задача слушателя для кнопки. Для начала: не нужно брать текст с кнопки, текст может измениться, а кнопка должна выполнять то же самое действие
5. Слушатели нужно задать в цикле и у всех кнопок желательно иметь одинаковый слушатель - например, функцию, которая в зависимости от переданного значения, будет вызывать нужное действие. Предупреждаю: не нужно передавать в функцию строку, это будет неэффективно, для этого можно использовать `enum class`. В данном случае предлагаю следующее:
- Создаём `enum`, в котором будут перечислены все возможные действия. Тогда можно сделать словарь, где ключ - это кнопка (ссылка через binding), а значение - это элемент этого `enum`
- Создаём функцию, которая на вход будет принимать значение этого `enum`, а внутри через `when` будет выбирать нужное действие
- А дальше можно просто пройтись по словарю через `forEach` и повесить на все кнопки один слушатель, в котором будет вызываться функция с соответствующим значением `enum`
Таким образом дублирования кода не будет вообще

Для первого раза, думаю, достаточно. Хорошая работа, молодец

**Comment by Sturm-noob** [comment]
fcf0e73
